workflows:
  android-workflow-id:
    name: QA workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
  ios-workflow-id:
    name: ios QA workflow
    max_build_duration: 120
    instance_type: mac_mini_m1