workflows:
  android-workflow-id:
    name: QA workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - firebase_credentials
    scripts:
      - name: Load Firebase configuration
        script: |
          echo $ANDROID_FIREBASE_JSON | base64--decode > $CM_BUILD_DIR/android/app/google-services.json
#          echo $IOS_FIREBASE_JSON | base64--decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release --build-name=1.0.0 --build-number=1
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:777924062407:android:3ddbf2f1fbdc4358d2e2e2
          groups:
            - internal
      slack:
        channel: "#build"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: true # To not receive a notification when a build fails

  ios-workflow-id:
    name: ios QA workflow
    max_build_duration: 120
    instance_type: mac_mini_m1